### ISSUE TITLE
Readme example doesn't work

### ISSUE THREAD

**Issue by joestringer** [KyleMayes/install-llvm-action#3]
Thanks for the convenient GH action script :-) 

For https://github.com/cilium/cilium/pull/13770 , I found that the readme example using the path `~/.clang` does not work, neither does `.clang`. However, if I configured it to `$HOME/.clang` then it would work.

**Comment by KyleMayes** [comment]
Thanks for the report, I changed the example directory to `${{ runner.temp }}/llvm` which is what I use in my projects and I know it works on every operating system.
