### ISSUE TITLE
LLVM 14.0.1 and later not supported on Ubuntu

### ISSUE THREAD

**Issue by KyleMayes** [KyleMayes/install-llvm-action#31]
The LLVM releases have not included Ubuntu binaries since 14.0.1.
Until this is changed this action will not be able to support these versions on Linux.
https://github.com/llvm/llvm-project/issues/57218

**Comment by aditya-solana** [comment]
available now: https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.6

**Comment by KyleMayes** [comment]
15.0.5 and 15.0.6 now supported on Ubuntu runners so at least we have some LLVM 15 coverage for Linux users.
