### ISSUE TITLE
Need a way to specify alternate architecture, for crosscompilation

### ISSUE THREAD

**Issue by steven-johnson** [KyleMayes/install-llvm-action#34]
e.g., on OSX, it would be reasonable to want to download aarch64 (even on x86_64 build machines) to allow for crosscompilation to the ARM macs. 

(What I *really* want is to be able to install a `universal2` install, ie with both x64 and arm64 in the libraries, but I don't think LLVM provides those from the download site... but if I could explicitly request both, I think I could use `lipo` to stitch together the pieces I need.)

**Comment by aminya** [comment]
setup-cpp allows providing the desired architecture. However, the variable is not wired for LLVM.

[setup-cpp](https://github.com/aminya/setup-cpp)

**Comment by KyleMayes** [comment]
This action mainly exists to support https://github.com/KyleMayes/clang-sys and friends.
So if you have a need for multiple platforms I'd recommend checking out https://github.com/aminya/setup-cpp.
