### ISSUE TITLE
Failed to install 15 version on Windows

### ISSUE THREAD

**Issue by silverqx** [KyleMayes/install-llvm-action#38]
LLVM stopped providing the exe for win64/32, [here](https://github.com/silverqx/TinyORM/actions/runs/3623408582/jobs/6109236443) is my action that failed with the 15.0.6 version, I have to downgrade back to the 14.0.6.

Now I check it [here](https://github.com/llvm/llvm-project/releases?page=1) and they don't provide any compiled package exe or archive for Windows 🤐, only source packages, omg.

**Comment by KyleMayes** [comment]
They seem to have added Win64 binaries since then?
In any case, the most recent version of this action supports 15.0.6 with Windows.

**Comment by silverqx** [comment]
How is that possible that they added them 8 days after the release? Did filled an issue at clang issues?
