### ISSUE TITLE
Add LLVM/Clang 16.0.0

### ISSUE THREAD

**Issue by SavchenkoValeriy** [KyleMayes/install-llvm-action#45]
The new version is out: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0 and it would be great to have it available as well.

**Comment by KyleMayes** [comment]
Support has been added, but they didn't release 16.0.0 for macOS so it won't work on that platform.

**Comment by SavchenkoValeriy** [comment]
@KyleMayes yep, I noticed that. My guess is that they stopped producing binaries for Intel Macs altogether.
Thanks for a blazing fast response and a great action!
