### ISSUE TITLE
ubuntu builds don't respect `download-url`

### ISSUE THREAD

**Issue by FreeMasen** [KyleMayes/install-llvm-action#57]
I believe [this function](https://github.com/KyleMayes/install-llvm-action/blob/master/index.ts#L251) should be considering the download-url but it appears to be ignoring that configuration?

**Comment by KyleMayes** [comment]
I guess the person who submitted that change only cared about macOS and I didn't notice.

I've released v1.9.0 that respects this option on Linux and Windows runners.
