### ISSUE TITLE
Incorrect list of Darwin versions

### ISSUE THREAD

**Issue by nazar-pc** [KyleMayes/install-llvm-action#61]
For example 17.0.2 does have Darwin build in it, just like any newer release.

Would be great to update the list accordingly in the code.

**Comment by nazar-pc** [comment]
Also 16.0.0 to 16.0.5 (inclusive) also all have darwin builds available.

**Comment by nazar-pc** [comment]
Hm... it also tries to download x86-64 version on arm64 runner for some reason and fails, which is not surprising because recent releases are arm64-only

**Comment by KyleMayes** [comment]
I've added [`v2.0.0`](https://github.com/KyleMayes/install-llvm-action/blob/master/CHANGELOG.md#200---2024-03-31) which reworks how download URLs are determined (now a script populates a JSON file by querying the GitHub API for the LLVM releases). This script has provided versions for the missing macOS versions and should make it much easier to add support for future LLVM and Clang versions.

Most users shouldn't need to change anything to move from `v1` to `v2`, see the above the link for what changed.

**Comment by nazar-pc** [comment]
Very nice, thank you!
