### ISSUE TITLE
dist/main.js hasn't been updated for a while; new LLVM versions are unavailable

### ISSUE THREAD

**Issue by gentoo-root** [KyleMayes/install-llvm-action#75]
When used as a GitHub action, dist/main.js is the code that runs, but it looks outdated: last change at https://github.com/KyleMayes/install-llvm-action/commit/8b37482c5a2997a3ab5dbf6561f8109e2eaa7d3b; the [change that adds 18.1.4 — 18.1.6](https://github.com/KyleMayes/install-llvm-action/commit/aeccb6041ecf8f9d0bb9cfb14e1511312ccc850c) is not included. dist/main.js needs to be recompiled and synced with the recent changes.

**Comment by KyleMayes** [comment]
Sorry for the long delay.
I have updated the code to load the assets dynamically (instead of importing them) so that the code doesn't need to be re-built.
The latest released version should now support LLVM/Clang versions up to 18.1.8 (for platforms with binaries available).
