### ISSUE TITLE
Include 18.1.8 for ARM-based Macs

### ISSUE THREAD

**Issue by SavchenkoValeriy** [KyleMayes/install-llvm-action#79]
Thanks so much for creating and maintaining this project 🏆 

2 weeks ago the LLVM team added the arm64 macos binary:
https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-arm64-apple-macos11.tar.xz

It would be nice to have it available for installation.

**Comment by KyleMayes** [comment]
Included in v2.0.5.

**Comment by SavchenkoValeriy** [comment]
Amazing, thank you for such a swift fix! 🏎️
